/**
 * An account represents a company interested
 * in our products. Inside an account it is
 * recorded every opportunity generated by
 * leads from this company. There is a one
 * to many relationship between account and
 * opportunity, and between opportunity and
 * contact which reflects in a one to many
 * relationship between account and contact.
 */

package CRMDataLayer.model;

import CRMDataLayer.enums.Activity;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

import lombok.*;

@Getter
@Setter
@AllArgsConstructor

@Entity
@Table(name="account")
public class Account {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Enumerated(EnumType.STRING)
    @Column(name="industry")
    private Activity industry;
    @Column(name="city")
    private String city; // This could also be a very long string of cities or an enum
    @Column(name="country")
    private String country; // same as city case

    // 1 account holds n opportunities -->
    // 1 opportunity holds 1 decisionMaker -->
    // 1 account holds n decisionMaker (contact)
    @OneToMany(mappedBy="account", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Opportunity> opportunities;

    @OneToMany(mappedBy="account", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Contact> contacts;

    public Account(Activity industry, String city, String country) {
        this.industry = industry;
        this.city = city;
        this.country = country;
    }

    public Account() {
        super();
        opportunities = new ArrayList<Opportunity>();
        contacts = new ArrayList<Contact>();
    }

    @Override
    public String toString() {
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        return gson.toJson(this) + "\n" + "    ────────────────────────────";
    }
}
